version: "3"
services:
  openbis:
    build: .
    container_name: "openbis"
    image: ghcr.io/mat-o-lab/openbismantic:main #will be changed to latest
    environment:
      SERVER_HOST_PORT: "${HOST_NAME}:${OPENBIS_SSL_PORT}"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ADMIN_PASS: ${ADMIN_PASS}
      GROUP_NAME: ${GROUP_NAME}
      GROUP_ID : ${GROUP_ID}
    restart: always
    networks:
      - openbis_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openbis"]
      interval: 15s
      timeout: 10s
      retries: 30
      start_period: 30s
  init_database:
    build:
      context: ./init_database
      dockerfile: ./Dockerfile
    container_name: init_database
    image: ghcr.io/mat-o-lab/openbismantic_init:main #will change to latest
    environment:
      SERVER_HOST_PORT: "openbis:443"
      ADMIN_PASS: ${ADMIN_PASS}
    depends_on:
      openbis:
        condition: service_healthy
    restart: "on-failure"
    networks:
      - openbis_net
  nginx:
    image: nginx:1.23.4-alpine
    ports:
      - ${OPENBIS_PORT}:80
      - ${OPENBIS_SSL_PORT}:443
    environment:
      OPENBIS_SSL_PORT: ${OPENBIS_SSL_PORT}
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      # openssl req -new -x509 -nodes -days 365 -newkey rsa:4096 -subj "/C=SW/ST=Basel-City/L=Basel/O=SSDM/CN=SIS" -keyout openbis.key -out openbis.crt
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - openbis_net
    depends_on:
      - openbis
      - vouch
  vouch:
    image: voucher/vouch-proxy:0.27.1
    volumes:
      - ./vouch:/config:ro
    networks:
      - openbis_net

networks:
  openbis_net:
    name: openbis_net
    driver: bridge
