vouch:
  domains:
    - xeo54
    - iwm.fraunhofer.de

  cookie:
    secure: false

  headers:
    idtoken: X-Vouch-IdP-IdToken
    claims:
      - sub
      - email
      - given_name
      - family_name
      - preferred_username

oauth:
  provider: oidc
  client_id: openbis
  client_secret: 6t0O0m0d32d3A5OejvZuyP9TmHxtirSB
  auth_url: http://xeo54:8000/realms/master/protocol/openid-connect/auth
  token_url: http://xeo54:8000/realms/master/protocol/openid-connect/token
  user_info_url: http://xeo54:8000/realms/master/protocol/openid-connect/userinfo
  scopes:
    - openid
    - email
    - profile
  callback_url: https://xeo54:8128/auth
